name: builder

on:
  workflow_call:
    inputs:
      # Clone Action
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      svnTarget:
        type: boolean
        default: false
      # Architecture Action
      architecture:
        type: string
      tplPacmanConf:
        type: string
      tplMakepkgConf:
        type: string
      confOutDir:
        type: string
      repoTag:
        type: string
      repoTagKey:
        type: string
      repoServer:
        type: string
      repoServerKey:
        type: string
      pkg:
        type: string
      updatePkg:
        type: boolean
        default: false
      # # Build Action
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false
      # # Upload Action
      upload:
        type: boolean
        default: true
      commit:
        type: boolean
        default: true 
  workflow_dispatch:
    inputs:
      # Clone Action
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      svnTarget:
        type: boolean
        default: false
      # Architecture Action
      architecture:
        type: string
      repoTag:
        type: string
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false
      # Upload Action
      upload:
        type: boolean
        default: true
      # Commit Action
      commit:
        type: boolean
        default: true 

jobs:
  package: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone Package
        id: clone
        uses: highkeep/pkgbuild_clone-action@v1.0
        with:
          repoUrl: ${{ inputs.repoUrl }}
          repoPkg: ${{ inputs.repoPkg }}
          svnTarget: ${{ inputs.svnTarget }}
      - name: Check version
        id: version
        uses: highkeep/pkgbuild_version-action@v1.0
        with:
          repoTag: ${{ inputs.repoTag }}
          pkg: ${{ steps.clone.outputs.pkg }}
          pkgRef: ${{ steps.clone.outputs.pkgRef }}
      - name: Setup Architecture
        if: ${{ steps.version.outputs.updatePkg == 'true' }}
        id: architecture
        uses: highkeep/pkgbuild_architecture-action@v1.0
        with:
          architecture: ${{ inputs.architecture }}
          tplPacmanConf: ${{ inputs.tplPacmanConf }}
          tplMakepkgConf: ${{ inputs.tplPacmanConf }}
          confOutDir: ${{ inputs.confOutDir }}
          repoTag: ${{ inputs.repoTag }}
          repoTagKey: ${{ inputs.repoTagKey }}
          repoServer: ${{ inputs.repoServer }}
          repoServerKey: ${{ inputs.repoServerKey }}
          pkg: ${{ steps.clone.outputs.pkg }}
          updatePkg: ${{ inputs.updatePkg }}
      - name: Print out conf files
        run: |
          echo "*************************************************************************"
          echo "*************************************************************************"
          echo "Contents of pacman.conf:"
          cat ${{ steps.architecture.outputs.pacmanConf }}
          echo "*************************************************************************"
          echo "*************************************************************************"
          echo "Contents of makepkg.conf:"
          cat ${{ steps.architecture.outputs.makepkgConf }}
          echo "*************************************************************************"
          echo "*************************************************************************"
      - name: Makepkg Build and Check
        if: ${{ fromJson(steps.version.outputs.updatePkg) == true }}
        id: makepkg
        uses: highkeep/pkgbuild-action@v1.1.9
        with:
          pkgdir: ${{ steps.clone.outputs.pkg }}
          pacmanConf: ${{ steps.architecture.outputs.pacmanConf }}
          makepkgConf: ${{ steps.architecture.outputs.makepkgConf }}
          makepkgArgs: ${{ inputs.makepkgArgs }}
          multilib: ${{ inputs.multilib }}
          nvidiaUtils: ${{ inputs.nvidiaUtils }}
          repoReleaseTag: ${{ steps.architecture.outputs.repoTag }}
      - name: Print Package Files
        if: ${{ (steps.version.outputs.updatePkg == 'true') && (github.event.inputs.upload == 'true') }}
        run: |
          echo "Successfully created the following package archive"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
          echo "Package: ${{ steps.makepkg.outputs.repofile0 }}"
          echo "Package: ${{ steps.makepkg.outputs.repofile1 }}"
          echo "Package: ${{ steps.makepkg.outputs.repofile2 }}"
          echo "Package: ${{ steps.makepkg.outputs.repofile3 }}"
      - uses: svenstaro/upload-release-action@v2
        if: ${{ (steps.version.outputs.updatePkg == 'true') && (github.event.inputs.upload == 'true') }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.pkgfile0 }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2
        if: ${{ (steps.version.outputs.updatePkg == 'true') && (github.event.inputs.upload == 'true') }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.repofile0 }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2
        if: ${{ (steps.version.outputs.updatePkg == 'true') && (github.event.inputs.upload == 'true') }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.repofile1 }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2
        if: ${{ (steps.version.outputs.updatePkg == 'true') && (github.event.inputs.upload == 'true') }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.repofile2 }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2
        if: ${{ (steps.version.outputs.updatePkg == 'true') && (github.event.inputs.upload == 'true') }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.repofile3 }}
          overwrite: true
      - name: Add & Commit
        if: ${{ (steps.version.outputs.updatePkg == 'true') && (github.event.inputs.commit == 'true') }}
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: ${{ steps.version.outputs.refFile }}
          fetch: true
          pull: --rebase --autostash