name: build

on:
  workflow_dispatch:
    inputs:
      repo_url:
        required: true
        type: string
      repo_pkg:
        required: true
        type: string
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false

  package: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ needs.architecture.outputs.ref }}
    - name: Clone Package
      run: |
        git clone ${{ inputs.repo_url }}/${{ inputs.repo_pkg }}.git
    - name: Set PKGBUILD architecture 
      run: |
        if [[ ${{ needs.architecture.outputs.ref }} != 'generic' ]]; then
          source functions.sh && setArch ${{ needs.architecture.outputs.build_arch }} ${{ inputs.repo_pkg }}/PKGBUILD
        fi
        cat ${{ inputs.repo_pkg }}/PKGBUILD
    - name: Makepkg Build and Check
      id: makepkg
      uses: highkeep/pkgbuild-action@master
      with:
        pkgdir: ${{ inputs.repo_pkg }}
        pacmanConf: "configs/${{ needs.architecture.outputs.build_arch }}_pacman.conf"
        makepkgConf: "configs/${{ needs.architecture.outputs.build_arch }}_makepkg.conf"
        makepkgArgs: ${{ inputs.makepkgArgs }}
        multilib: ${{ inputs.multilib }}
        nvidiaUtils: ${{ inputs.nvidiaUtils }}