name: build

on:
  workflow_call:
    inputs:
      # Clone Action
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      svnTarget:
        type: boolean
        default: false
      # Architecture Action
      architecture:
        type: string
      tplPacmanConf:
        type: string
      tplMakepkgConf:
        type: string
      confOutDir:
        type: string
      repoTag:
        type: string
      repoTagKey:
        type: string
      repoServer:
        type: string
      repoServerKey:
        type: string
      pkg:
        type: string
      updatePkg:
        type: boolean
        default: false
      # # Build Action
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false
      # # Upload Action
      upload:
        type: boolean
        default: true
      commit:
        type: boolean
        default: true 
  workflow_dispatch:
    inputs:
      # Clone Action
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      svnTarget:
        type: boolean
        default: false
      # Architecture Action
      architecture:
        type: string
      repoTag:
        type: string
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false
      # Upload Action
      upload:
        type: boolean
        default: true
      commit:
        type: boolean
        default: true 

jobs:
  package: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone Package
        id: clone
        uses: highkeep/pkgbuild_clone-action@main
        with:
          repoUrl: ${{ inputs.repoUrl }}
          repoPkg: ${{ inputs.repoPkg }}
          svnTarget: ${{ inputs.svnTarget }}
      - name: Check version
        id: version
        uses: highkeep/pkgbuild_version-action@main
        with:
          repoTag: ${{ inputs.repoTag }}
          pkg: ${{ steps.clone.outputs.pkg }}
          pkgRef: ${{ steps.clone.outputs.pkgRef }}
      - name: Setup Architecture
        if: ${{ steps.version.outputs.updatePkg == 'true' }}
        id: setupArch
        uses: highkeep/pkgbuild_architecture-action@main
        with:
          architecture: ${{ inputs.architecture }}
          tplPacmanConf: ${{ inputs.tplPacmanConf }}
          tplMakepkgConf: ${{ inputs.tplPacmanConf }}
          confOutDir: ${{ inputs.confOutDir }}
          repoTag: ${{ inputs.repoTag }}
          repoTagKey: ${{ inputs.repoTagKey }}
          repoServer: ${{ inputs.repoServer }}
          repoServerKey: ${{ inputs.repoServerKey }}
          pkg: ${{ steps.clone.outputs.pkg }}
          updatePkg: ${{ inputs.updatePkg }}
      # - name: Makepkg Build and Check
      #   if: ${{ steps.version.outputs.updatePkg == 'true' }}
      #   id: makepkg
      #   uses: highkeep/pkgbuild-action@master
      #   with:
      #     pkgdir: ${{ steps.clone.outputs.pkg }}
      #     pacmanConf: ${{ steps.setupArch.outputs.pacmanConf }}
      #     makepkgConf: ${{ steps.setupArch.outputs.makepkgConf }}
      #     makepkgArgs: ${{ inputs.makepkgArgs }}
      #     multilib: ${{ inputs.multilib }}
      #     nvidiaUtils: ${{ inputs.nvidiaUtils }}
      # - name: echo repofiles and pkgfiles
      #   run: |
      #     echo ${{ steps.makepkg.outputs.repofiles }}
      #     echo ${{ steps.makepkg.outputs.pkgfiles }}
      - uses: svenstaro/upload-release-action@v2
        if: ${{ steps.version.outputs.updatePkg && inputs.upload == 'true' }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.pkgfile0 }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2
        if: ${{ steps.version.outputs.updatePkg && inputs.upload == 'true' }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.repofile0 }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2
        if: ${{ steps.version.outputs.updatePkg && inputs.upload == 'true' }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.repofile1 }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2
        if: ${{ steps.version.outputs.updatePkg && inputs.upload == 'true' }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.repofile2 }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2
        if: ${{ steps.version.outputs.updatePkg && inputs.upload == 'true' }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ steps.architecture.outputs.repoTag }}
          file: ${{ steps.makepkg.outputs.repofile3 }}
          overwrite: true
      - name: Add & Commit
        if: ${{ steps.version.outputs.updatePkg && github.event.inputs.commit == 'true' }}
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: ${{ steps.version.outputs.refFile }}
          fetch: true
          pull: --rebase
  # test: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Version
  #       id: version
  #       run: |
  #         echo "updatePkg=true">>$GITHUB_OUTPUT
  #     - name: Test 1
  #       run: |
  #         echo ${{ steps.version.outputs.updatePkg }}
  #         echo ${{ inputs.commit }}
  #         echo ${{ github.event.inputs.commit }}
  #     - name: Test 2
  #       if: ${{ steps.version.outputs.updatePkg == 'true' }} && ${{ github.event.inputs.commit == 'true' }}
  #       run: |
  #         echo Test 2 Ran
  #     - name: Test 3
  #       if: |
  #         ${{ steps.version.outputs.updatePkg == 'true' }} && ${{ github.event.inputs.commit == 'true' }}
  #       run: |
  #         echo Test 3 Ran
  #     - name: Test 4
  #       if: ${{ steps.version.outputs.updatePkg && github.event.inputs.commit == 'true' }}
  #       run: |
  #         echo Test 4 Ran
  #     - name: Test 5
  #       if: |
  #         ${{ steps.version.outputs.updatePkg == 'true' && inputs.commit == 'true' }}
  #       run: |
  #         echo Test 5 Ran
