name: build

on:
  workflow_dispatch:
    inputs:
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false
      arch:
        type: string
        default: alderlake
      svnTarget:
        type: boolean
        default: false

jobs:
  package: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone Package
        id: clone
        uses: highkeep/makepkg_clone-action@main
        with:
          repoUrl: ${{ inputs.repoUrl }}
          repoPkg: ${{ inputs.repoPkg }}
          svnTarget: ${{ inputs.svnTarget }}
      - name: echo pkg 
        run: |
          echo ${{ steps.clone.outputs.pkg }}
          echo ${{ steps.clone.outputs.pkgRef }}
      - name: Setup
        id: setup
        uses: highkeep/makepkg_architecture-action@main
        with:
          tplPacmanConf: configs/tpl_pacman.conf
          tplMakepkgConf: configs/tpl_makepkg.conf
          pkg: ${{ steps.clone.outputs.pkg }}
      # - name: Set PKGBUILD architecture 
      #   run: |
      #     if [[ ${{ inputs.arch }} != 'generic_x86_64' ]]; then
      #       source functions.sh && setArch ${{ inputs.arch }} ${{ inputs.repo_pkg }}/PKGBUILD
      #     fi
      #     cat ${{ inputs.repo_pkg }}/PKGBUILD
      # - name: Makepkg Build and Check
      #   id: makepkg
      #   uses: highkeep/pkgbuild-action@master
      #   with:
      #     pkgdir: ${{ inputs.repo_pkg }}
      #     pacmanConf: "configs/${{ inputs.arch }}_pacman.conf"
      #     makepkgConf: "configs/${{ inputs.arch }}_makepkg.conf"
      #     makepkgArgs: ${{ inputs.makepkgArgs }}
      #     multilib: ${{ inputs.multilib }}
      #     nvidiaUtils: ${{ inputs.nvidiaUtils }}