name: build_matrix

on:
  workflow_dispatch:
    inputs:
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      architecture:
        required: true
        type: string
        default: '["generic", "alderlake"]'
      svnTarget:
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=$architecture" >> $GITHUB_OUTPUT
        env:
          architecture: ${{ github.event.inputs.architecture }}
  process:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        architecture: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Print
        run: |
          echo ${{ github.event.inputs.repoUrl }}
          echo ${{ github.event.inputs.repoPkg }}
          echo ${{ github.event.inputs.svnTarget }}
          echo ${{ matrix.architecture }}
      # - uses: highkeep/pkgbuilder/.github/workflows/test.yml@main
      #   with:
      #     repoURL: ${{ github.event.inputs.repoUrl }}
      #     repoPkg: ${{ github.event.inputs.repoPkg }}
      #     svnTarget: ${{ github.event.inputs.svnTarget }}
      #     architecture: ${{ matrix.architecture }}