name: matrix

on:
  workflow_dispatch:
    inputs:
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false
      svnTarget:
        type: boolean
        default: false
      art:
        description: "JSON combined architecture and repoTag"
        required: true
        type: string
 
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      art: ${{ steps.set-matrix.outputs.art }}
    steps:
      - id: set-matrix
        run: |
          echo "art={\"include\":$art}" >> $GITHUB_OUTPUT
        env:
          art: ${{ github.event.inputs.art }}
  process:
    needs: setup
    # runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.art)}}
        # art: ${{fromJson(needs.setup.outputs.art)}}
    uses: highkeep/pkgbuilder/.github/workflows/test.yml@matrix
    with:
      repoURL: ${{ github.event.inputs.repoUrl }}
      repoPkg: ${{ github.event.inputs.repoPkg }}
      svnTarget: ${{ fromJson(github.event.inputs.svnTarget) }}
      architecture: ${{ matrix.architecture }}
      repoTag: ${{ matrix.repoTag }}
    # steps:
    #   - run: |
    #       echo ${{ matrix }}
    #       echo ${{ matrix.architecture }}
    #       echo ${{ matrix.repoTag }}
