name: matrix

on:
  workflow_dispatch:
    inputs:
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      # architecture:
      #   required: true
      #   type: string
      #   default: ""
      svnTarget:
        type: boolean
        default: false
      art:
        description: "JSON combined architecture and repoTag"
        required: true
        type: string
 
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      art: ${{ steps.set-matrix.outputs.art }}
    steps:
      - id: set-matrix
        run: |
          echo "art=$art" >> $GITHUB_OUTPUT
        env:
          art: ${{ github.event.inputs.arch_repoTag }}
  process:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        art: ${{fromJson(needs.setup.outputs.art)}}
    uses: highkeep/pkgbuilder/.github/workflows/test.yml@main
    with:
      repoURL: ${{ github.event.inputs.repoUrl }}
      repoPkg: ${{ github.event.inputs.repoPkg }}
      svnTarget: ${{ fromJson(github.event.inputs.svnTarget) }}
      architecture: ${{ matrix.art.architecture }}
      repoTag: ${{ matrix.art.repoTag }}
    # steps:
    #   - run: |
    #       echo ${{ matrix.arch }}
    #       echo ${{ matrix.repoTag }}
    #       echo ${{ matrix.arch_repoTag }}
    #       echo ${{ matrix.arch_repoTag.arch }}
    #       echo ${{ matrix.arch_repoTag.repoTag }}
