name: multiarch_builder

on:
  workflow_call:
    inputs:
      repoUrl:
        description: "GIT repository: https://aur.archlinux.org/<SomePkg>.git"
        required: true
        type: string
      repoPkg:
        description: "Package's name: <SomePkg>"
        required: true
        type: string
      svnTarget:
        description: "Clone <SomePkg> with svn"
        type: boolean
        default: false
      art:
        description: "JSON combined architecture and repoTag"
        required: true
        type: string
        default: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
      makepkgArgs:
        description: "Add additional arguments to makepkg."
        type: string
      multilib:
        description: "Add multilib"
        type: boolean
        default: false
      nvidiaUtils:
        description: "Add nvidia-utils and lib32-nvidia-utils"
        type: boolean
        default: false
      upload:
        description: "Upload built package"
        type: boolean
        default: true
      commit:
        description: "Commit version changes"
        type: boolean
        default: true 
  workflow_dispatch:
    inputs:
      repoUrl:
        description: "GIT repository: https://aur.archlinux.org/<SomePkg>.git"
        required: true
        type: string
      repoPkg:
        description: "Package's name: <SomePkg>"
        required: true
        type: string
      svnTarget:
        description: "Clone <SomePkg> with svn"
        type: boolean
        default: false
      art:
        description: "JSON combined architecture and repoTag"
        required: true
        type: string
        default: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
      makepkgArgs:
        description: "Add additional arguments to makepkg."
        type: string
      multilib:
        description: "Add multilib"
        type: boolean
        default: false
      nvidiaUtils:
        description: "Add nvidia-utils and lib32-nvidia-utils"
        type: boolean
        default: false
      upload:
        description: "Upload built package"
        type: boolean
        default: true
      commit:
        description: "Commit version changes"
        type: boolean
        default: true 
 
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      art: ${{ steps.set-matrix.outputs.art }}
    steps:
      - id: set-matrix
        run: |
          echo "art={\"include\":$art}" >> $GITHUB_OUTPUT
        env:
          art: ${{ github.event.inputs.art }}
  process:
    needs: setup
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.art)}}
    uses: highkeep/pkgbuild/.github/workflows/build.yml@v1.0
    with:
      repoURL: ${{ github.event.inputs.repoUrl }}
      repoPkg: ${{ github.event.inputs.repoPkg }}
      makepkgArgs: ${{ github.event.inputs.makepkgArgs }}
      multilib: ${{ inputs.multilib }}
      nvidiaUtils: ${{ inputs.nvidiaUtils }}
      svnTarget: ${{ inputs.svnTarget }}
      architecture: ${{ matrix.architecture }}
      repoTag: ${{ matrix.repoTag }}
      upload: ${{ inputs.upload }}
      commit: ${{ inputs.commit }}