name: proton

on:
  workflow_dispatch:
 
env:
  architectures: "{\"include\":[{\"arch\":\"generic\"}, {\"arch\":\"alderlake\"]}"
 
jobs:
  build:
    runs-on: ubuntu-latest
    # environment: build
    strategy:
      matrix: ${{ env.architectures }}
        # arch: ${{ fromJSON(vars.ARCHITECTURES) }}
        # arch: ${{ fromJSON(env.architectures) }}
    steps:
      - run: |
          echo ${{ matrix.arch }}
