name: proton

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    strategy:
      matrix:
        arch: ${{ fromJson(vars.ARCHITECTURES) }}
    steps:
      - run: |
          echo ${{ matrix.arch }}
