name: proton

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    strategy:
      matrix:
        ${{ vars.ARCHITECTURES }}
    steps:
      - run: |
          echo ${{ matrix.architectures }}
