name: proton

on:
  workflow_dispatch:

env:
  architectures: "[\"generic\", \"alderlake\"]"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ${{ fromJSON(env.architectures) }}
    steps:
      - run: |
          echo ${{ matrix.arch }}
