name: test

on:
  workflow_call:
    inputs:
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      svnTarget:
        type: boolean
        default: false
      architecture:
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo ${{ github.event.inputs.repoUrl }}
          echo ${{ github.event.inputs.repoPkg }}
          echo ${{ github.event.inputs.svnTarget }}
          echo ${{ matrix.architecture }}