name: test

on:
  workflow_call:
    inputs:
      repoUrl:
        required: true
        type: string
      repoPkg:
        required: true
        type: string
      svnTarget:
        type: boolean
        default: false
      architecture:
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo $repoURL
          echo $repoPKG
          echo $scnTarget
          echo $architecture